version: 2
jobs:
  build_and_test:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
            - dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          name: Save node_modules cache
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Build
          command: yarn compile
      - run:
          name: Test
          command: yarn test

